---

- name: enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  become: yes
  with_items:
    - "nfs-server"
    - "firewalld"

#configurar el acceso al share de NFS
- name: copy files
  copy:
    src: "{{ item }}"
    dest: "/etc/{{ item }}"
    mode: '0644'
  become: yes
  with_items:
      - "exports"

# exportfs -r
- name: enable repository
  command: "/etc/exports exportfs -r"
  become: yes
  become_method : sudo


# exportfs -s
- name: exec repository
  command: "/etc/exports exportfs -s"
  become: yes
  become_method : sudo