---

- name: enable epel repository
  command: "/usr/bin/dnf -y install {{ epel_repo }}"
  become: yes

- name: enable powertools repository
  command: "/usr/bin/dnf config-manager --set-enabled powertools"
  become: yes
  
# timedatectl set-timezone Europe/Madrid
- name: Set timezone to Europe/Madrid
  timezone:
    name: Europe/Madrid

# dnf install chrony -y
- name: install packages
  dnf:
    name: "{{ common_rpms }}"
    state: latest
  become: yes

# systemctl enable chronyd
# systemctl start chronyd
- name: enable services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    masked: no
  become: yes
  with_items:
    - "chronyd"

- name: timedatectl true
  command: "timedatectl set-ntp true"
  become: yes

# sed -i s/=enforcing/=disabled/g /etc/selinux/config
#- name: enable powertools repository
#  command: "/etc/selinux/config sed -i s/=enforcing/=disabled/g"
#  become: yes