---

# activar transparent masquerading para que los PODs puedan comunicarse dentro del cluster mediante VXLAN
# modprobe br_netfilter
- name: enable transparent masquerading 
  command: "modprobe br_netfilter"
  become: yes

# firewall-cmd --add-masquerade --permanent