---
  
  #tráfico con el cortafuegos
- name: copy files
  copy:
    src: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  become: yes
  with_items:
      - "kubernetes.repo"

- name: instalando kubelet kubeadm kubectl
  dnf:
    name: "{{ kubernetes_rpms }}"
    state: present
  become: yes

- name: instalando kubelet kubeadm kubectl
  dnf:
    name:
     - kubernetes
    state: absent
  become: yes

- name: configurando el arranque
  systemd:
    name: kubelet
    state: started
    enabled: yes
    masked: no
  become: yes