---

#Creamos un usuario no administrador para la gestión del clúster:

- name: Create a directory if it does not exist
  file:
    path: /home/kubeadmin/.kube
    state: directory
    mode: '0755'
  become: yes

- name: Auth user cluster access
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kubeadmin/.kube/config
    owner: root
    group: root
    mode: '0755'
    remote_src: yes
  become: yes

- name: Auth user
  file:
    path: /home/kubeadmin/.kube/config
    owner: root
    group: root
  become: yes
