---

#Creamos un usuario no administrador para la gestión del clúster:

- name: Create a directory if it does not exist
  file:
    path: /home/kubeadmin/.kube
    state: directory
    mode: '0644'

- name: Auth user cluster access
  command: "cp -i /etc/kubernetes/admin.conf /home/kubeadmin/.kube/config"
  become: yes

- name: Auth user
  command: "chown kubeadmin. /home/kubeadmin/.kube/config"
  become: yes