---

# Configuramos el firewall para acceder a los servicios de kubernetes:
- name: firewall configuration1 for master
  firewalld:
    port: 6443/tcp
    permanent: yes
    state: enabled
    immediate: yes
  become: true

- name: firewall configuration2 for master
  firewalld:
    port: 2379-2380/tcp
    permanent: yes
    state: enabled
    immediate: yes
  become: true

- name: firewall configuration3 for master
  firewalld:
    port: 10250/tcp
    permanent: yes
    state: enabled
    immediate: yes
  become: true

- name: firewall configuration4 for master
  firewalld:
    port: 10251/tcp
    permanent: yes
    state: enabled
    immediate: yes
  become: true

- name: firewall configuration5 for master
  firewalld:
    port: 10252/tcp
    permanent: yes
    state: enabled
    immediate: yes
  become: true

- name: firewall configuration6 for master
  firewalld:
    port: 10255/tcp
    permanent: yes
    state: enabled
    immediate: yes
  become: true

# Configuramos kudeadm descargando imágenes
- name: kubeadm images download
  command: "kubeadm config images pull"
  become: yes

# Permitir acceso desde los workers
- name: worker01
  firewalld:
    rich_rule: rule family=ipv4 source address=10.0.1.11/16 accept
    permanent: yes
    immediate: yes
    state: enabled

- name: worker02
  firewalld:
    rich_rule: rule family=ipv4 source address=10.0.1.12/16 accept
    permanent: yes
    immediate: yes
    state: enabled

#Permitimos el acceso de los contenedores a localhost:
- name: docker
  firewalld:
    rich_rule: rule family=ipv4 source address=172.17.0.0/16 accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
