---

# Configuramos el firewall para acceder a los servicios de kubernetes:
- name: firewall configuration1 for master
  firewalld:
    port: {10250,30000-32767}/tcp
    zone: public
    permanent: yes
    state: enabled
    immediate: yes
  become: true

- name: firewall-cmd --reload 
  command: "firewall-cmd --reload"
  become: yes

# Configuramos kudeadm descargando imágenes
- name: kubeadm images download
  command: "kubeadm config images pull"
  become: yes
